image: maven:3.8.4-jdk-11

variables:
  DB_URL:  $DB_URL
  DB_USER: $DB_USER
  DB_PASSWORD: $DB_PASSWORD

stages:
  - tests

tests:
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .m2/repository
  stage: tests
  script:
    - echo "DB_URL=$DB_URL" >> .env
    - echo "DB_USER=$DB_USER" >> .env
    - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
    - mvn install:install-file -Dfile=ojdbc8.jar -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=19.3 -Dpackaging=jar -DskipTests
    - mvn test

